TANGLISH_CORRECTIONS = {

    # ===== Stable English loanwords in Tamil script =====
    # Safe because they are usually standalone complete words
    "கிராமராஜ் காட்டணன்": "Ramraj Cotton",
    "வேட்டினிருவனத்தில்": "Dhoti Company",
    "ராமராஜ்": "Ramraj",
    "காட்டணன்": "Cotton",
    "வேட்டி": "Dhoti",
    "சட்டு": "Shirt",
    "சட்ட": "Shirt",
    "நாய்ஸ்": "noise",
    "நாயிஸ்": "noise",
    "தோசை": "dosa",
    "இட்லி": "idli",
    "பிரியாணி": "biryani",
    "பில்டர்": "filter",
    "போண்டா": "bondai",
    "வேஷ்டி": "Veshti",
    "சாம்ராஜ்": "Ramraj",
    "ராம்ராஜ்": "Ramraj",
    "ராம்ராஜின்": "Ramraj",
    "ராம்ராஜை": "Ramraj",
    "ராம்ராஜின்": "Ramraj",
    "ராம்ராஜின்": "Ramraj",
    "ராம்ராஜின்": "Ramraj",

    
    # --- NEW from Ramraj Cotton interview ---
    "வேட்டித்": "Dhoti",
    "வேஷ்டி": "Dhoti",
    "வேஷ்டிகள்": "Dhotis",
    "வேட்டிகள்": "Dhotis",
    "காட்டன்": "Cotton",
    "காத்தின்": "Cotton",
    "திருப்புர்ல": "Tiruppur",
    
    "எட்டாட்டு": "Eight Eight",
    "கடத்தை": "Shop",
    "கடை": "Shop",
    "கடையை": "Shop",
    "மணிக்கு": "at",
    "மெல்வாக்கில்": "By the hour",
    "மணிவாக்கில்": "By the hour",
    "சுத்தியிருக்கும்": "Surroundings",
    "திருப்பு": "Tiruppur",
    "திருப்புர்": "Tiruppur",
    "கிராவப்புர": "Village side",
    "னேஸ் வளர்கள்":"Weavers",
    "நெசவாளர்கள்": "Weavers",
    "பண்ண": "made",
    "பண்ணி": "made",
    "பண்ணிய": "made",
    "பண்ணியிருக்க": "made",
    "பண்ணியிருக்கேன": "made",
    "பண்ணியிருக்கேனா": "made",
    "பண்ணியிருக்கேன": "made",
    "பண்ணியிருக்கேனா": "made",
    
    

        





    "சோ": "so",
    "ஃப்ரியா":"Free ah",
    "மீட்டிங்": "meeting",
    "மீட்டின்": "meeting",
    "ஜாய்ன்": "join",
    "ஜாயின்": "join",
    "ஆபீஸ்": "office",
    "டீம்": "team",
    "மேனேஜர்": "manager",
    "டாஸ்க்": "task",
    "ப்ராஜெக்ட்": "project",
    "இன்டர்வியூ": "interview",
    "ரெஸ்யூம்": "resume",
    "சாலரி": "salary",
    "போனஸ்": "bonus",

    # ===== Tech & Hardware =====
    "போன்": "phone",
    "மொபைல்": "mobile",
    "லாப்டாப்": "laptop",
    "கம்ப்யூட்டர்": "computer",
    "சிஸ்டம்": "system",
    "சர்வர்": "server",
    "டேட்டா": "data",
    "நெட்வொர்க்": "network",
    "வைஃபை": "wifi",
    "ஹாட்ஸ்பாட்": "hotspot",
    "ப்ளூடூத்": "bluetooth",
    "ரூட்டர்": "router",
    "ஸ்கிரீன்": "screen",
    "கீபோர்டு": "keyboard",
    "மவுஸ்": "mouse",
    "சார்ஜர்": "charger",

    # ===== Programming & IT =====
    "கோடு": "code",
    "கோடிங்": "coding",
    "ப்ரோக்ராம்": "program",
    "ப்ரோக்ராமிங்": "programming",
    "டெவலப்பர்": "developer",
    "டீபக்": "debug",
    "பக்": "bug",
    "எரர்": "error",
    "எக்ஸெப்ஷன்": "exception",
    "கம்பைல்": "compile",
    "பில்ட்": "build",
    "டிப்ளாய்": "deploy",
    "ஃப்ரேம்வொர்க்": "framework",
    "லைப்ரரி": "library",
    "மொட்யூல்": "module",
    "பேக்கேஜ்": "package",
    "டேட்டாபேஸ்": "database",
    "ஏபிஐ": "api",
    "க்ளவுட்": "cloud",
    "கோடுபேஸ்": "codebase",

    # ===== File / Software =====
    "பைல்": "file",
    "போல்டர்": "folder",
    "டாக்குமென்ட்": "document",
    "பிடிஎப்": "pdf",
    "எக்செல்": "excel",
    "வேர்ட்": "word",
    "பிபிடி": "ppt",
    "ப்ரௌசர்": "browser",
    "டெர்மினல்": "terminal",
    "கமாண்ட்": "command",

    # ===== Internet & Social Media =====
    "குரோம்": "chrome",
    "கூகுள்": "google",
    "யூடியூப்": "youtube",
    "ஜிமெயில்": "gmail",
    "வாட்ஸ்அப்": "whatsapp",
    "டெலிகிராம்": "telegram",
    "இன்ஸ்டாகிராம்": "instagram",
    "லிங்க்டின்": "linkedin",
    "ட்விட்டர்": "twitter",
    "ஃபேஸ்புக்": "facebook",
    "இன்டர்நெட்": "internet",
    "வெப்சைட்": "website",
    "ஆப்": "app",

    # ===== Communication & Actions =====
    "கால்": "call",
    "மெசேஜ்": "message",
    "டெக்ஸ்ட்": "text",
    "சாட்": "chat",
    "ரிப்ளை": "reply",
    "மெயில்": "mail",
    "ஈமெயில்": "email",
    "லிங்க்": "link",
    "ஜூம்": "zoom",
    
    "அப்டேட்": "update",
    "டவுன்லோடு": "download",
    "அப்லோடு": "upload",
    "இன்ஸ்டால்": "install",
    "அன்இன்ஸ்டால்": "uninstall",
    "லாகின்": "login",
    "லாக்அவுட்": "logout",
    "கனெக்ட்": "connect",
    "டிஸ்கனெக்ட்": "disconnect",
    "செண்ட்": "send",
    "ரிசீவ்": "receive",

    # ===== AI / Data =====
    "ஏஐ": "ai",
    "என்எல்பி": "nlp",
    "சாட்பாட்": "chatbot",
    "மாடல்": "model",
    "டேட்டாசெட்": "dataset",
    "அல்காரிதம்": "algorithm",

    # ===== Misc stable words =====
    "டிக்கெட்": "ticket",
    "பேமென்ட்": "payment",
    "பில்": "bill",
    "கேஷ்": "cash",
    "பேங்க்": "bank",
    "அக்கவுண்ட்": "account",
    "பாஸ்வேர்ட்": "password",
    "யூசர்": "user",
    "நம்பர்": "number",
    "ஸ்டேட்டஸ்": "status",
    "டைம்": "time",
    "டேட்": "date",
    "டெஸ்ட்": "test",
    "லைவ்": "live"
}
